### ISSUE TITLE
Make workers easy to setup on different machines (Metcentrum)

### ISSUE THREAD

**Issue by petrs** [crocs-muni/randomness-testing-toolkit#34]

**Comment by ph4r05** [comment]
I think we have this covered now, the workers can be deployed on the Metacentrum. 
We can improve the deployment scripts still.

Todo:
- [] deployment script for metacentrum workers
- [] prepare docker for building worker binaries, deployable on real machines

**Comment by Bender250** [comment]
Closed in https://github.com/crocs-muni/randomness-testing-toolkit/pull/37
