### ISSUE TITLE
Unable to pass rtt data file path (-f) with a space in it

### ISSUE THREAD

**Issue by maxwell-pung-bsi** [crocs-muni/randomness-testing-toolkit#50]
I am trying to run rtt big big crush battery and pass it a 100GB file from an external usb drive with the following command.
```bash
$ ./randomness-testing-toolkit -b tu01_bigcrush -f "/media/dev/My Drive/output-100GB.bin" -r file_report -c configuration_files/default-100GB.json
```
This results in the following error:
```
[Invalid toolkit configuration] command line argument "-f": can't convert "/media/dev/My Drive/output-100GB.bin"
```
Am I doing something wrong?

**Comment by mbroz** [comment]
If it works with a path without spaces, then it is clear bug here. It will be on more places I guess...

**Comment by maxwell-pung-bsi** [comment]
It does work without spaces. I changed the name of the external drive so it has no spaces and everything works well.
