### ISSUE TITLE
Using RTT w/ booltest

### ISSUE THREAD

**Issue by maxwell-pung-bsi** [crocs-muni/randomness-testing-toolkit#57]
The README states that RTT implements support for the booltest statistical tool. However, this seems to be the only place that this is mentioned and the CLI does not have any options for it. Is there a version of the RTT package somewhere that supports booltest?

**Comment by mbroz** [comment]
Unfortunately, there is no RTT version that supports Booltest yet. AFAIK there were plans to add it, but then colleagues used separate scripts and never implemented it in RTT.

We will perhaps switch to different RTT wrapper writen in Python, as the current architecture is really unmainainable. Once this happens, we will add Booltest and perhaps other tests as well.

**Comment by mbroz** [comment]
I have edited the README to mention it in fa8ecfb5fd7307ce9da21bf5828adaa491271cbf
