### ISSUE TITLE
How to use mysql storage to store execution results?

### ISSUE THREAD

**Issue by maxwell-pung-bsi** [crocs-muni/randomness-testing-toolkit#58]
I am working on getting rtt working w/ mysql db storage and need some guidance as I am running into issues.

What I have done so far is...
1. Installed mysql and the libmysqlcppconn-dev dependency. Verified mysql service is started and listening on port 3306.
2. Created the rtt tables using create_rtt_tables.sql
3. Added an experiment record using the following SQL statement
`INSERT INTO rtt.experiments (name, author_email, config_file, data_file, data_file_sha256) values ('My Name', 'My Email', '<full-path-to-default-8GB-json-file>', '<full-path-to-8GB-data-file>', '<sha-256-of-8GB-data-file>')`
4. Verified the record was created in the rtt.experiments table with an id of 1
5. Updated rtt-settings.json as follows
```json
"mysql-db": {
    "address": "127.0.0.1",
    "name": "rtt",
    "port": "3306",
    "credentials-file": "db-credentials.json"
}
```
6. Created db-credentials.json file in the root off randomness-test-toolkit directory as follows
```json
{
    "credentials": {
        "username": "root",
        "password": "<my-password>"
    }
}
```
7. Executed RTT as follows
`./randomness-testing-toolkit -b dieharder -f <path-to-8GB-data-file> -c configuration_files/default-8GB.json -r db_mysql --eid 1`

The output of this command indicates that dieharder was ran successfully against the file but pinging the database failed (as shown below).
```
[10:39:05] Thread 139649617647424: INFO  - Dieharder: Test execution finished!
[10:39:05] Thread 139649617647424: WARN  - Ping DB failed path 1
[10:39:05] Thread 139649617647424: ERROR - Ping DB failed, trying to reconnect
[10:39:05] Thread 139649617647424: ERROR - Unknown column 'job_id' in 'field list'
[10:39:05] Thread 139649617647424: WARN  - Ping DB failed path 1
[10:39:05] Thread 139649617647424: ERROR - Ping DB failed, trying to reconnect
[10:39:05] Thread 139649617647424: ERROR - Unknown column 'job_id' in 'field list'
```

From the documentation I quote:
```
Table jobs is not used by RTT directly, it server to scheduling cumputational jobs on deployed servers.

This database storage can be used for deploying RTT as a service.
```

Any advice regarding what I may be doing wrong or misunderstanding? I am not deploying RTT as service, I am running it directly.

**Comment by mbroz** [comment]
Hi, I am afraid there is currently nobody who acively uses mysql backend (I try to not break mysql but I do not actively using it). 

Anyway @ph4r05 has old repositories for web UI deployment (see https://github.com/ph4r05/rtt-deployment but perhaps also other repos), there could be some hints and perhaps even updated database schema.

**Comment by maxwell-pung-bsi** [comment]
Thanks for information!
